const UNIVERSITY_NAMES: Record<string, string> = {
  stanford: 'Stanford University',
  gatech: 'Georgia Institute of Technology',
  uga: 'University of Georgia',
  mit: 'Massachusetts Institute of Technology',
  umich: 'University of Michigan',
  uf: 'University of Florida',
  jhu: 'Johns Hopkins University',
  columbia: 'Columbia University',
  upenn: 'University of Pennsylvania',
  harvard: 'Harvard University',
  utaustin: 'University of Texas at Austin',
  ucsystem: 'University of California System',
  cornell: 'Cornell University',
  cmu: 'Carnegie Mellon University',
  uiuc: 'University of Illinois Urbana-Champaign',
  warf: 'Wisconsin Alumni Research Foundation',
  uw: 'University of Washington',
  purdue: 'Purdue University',
  minnesota: 'University of Minnesota',
  northwestern: 'Northwestern University',
  buffalo: 'University at Buffalo',
  unlv: 'University of Nevada Las Vegas',
  waynestate: 'Wayne State University',
  ucf: 'University of Central Florida',
  colorado: 'University of Colorado',
  usc: 'University of Southern California',
  usu: 'Utah State University',
  ttu: 'Texas Tech University',
  uconn: 'University of Connecticut',
  louisville: 'University of Louisville',
  iowa: 'University of Iowa',
  princeton: 'Princeton University',
  michiganstate: 'Michigan State University',
  texasstate: 'Texas State University',
  duke: 'Duke University',
}

export function getUniversityName(code: string): string {
  return UNIVERSITY_NAMES[code] || code
}
