export { DiscoveryPage } from './DiscoveryPage'
export { DashboardPage } from './DashboardPage'
export { BrowserPage } from './BrowserPage'
export { DetailPage } from './DetailPage'
export { OpportunitiesPage } from './OpportunitiesPage'
export { QAPage } from './QAPage'
export { QAReviewPage } from './QAReviewPage'
